### ISSUE TITLE
Can I use BOA to play other Doom WADs?

### ISSUE THREAD

**Issue by HellsBells24** [mcphail/boa#2]
I have a collection of Doom WADs on my Linux machine such as the original games (from Steam), Freedoom, Chex Quest, etc. I notice that BOA installs GZDoom along side the game itself and am wondering if it is possible for me to play these WADs with the BOA snap since, as I understand it, it is really just GZDoom. I would much rather use GZDoom by way of a Canonical approved SNAP package than I would a copy of GZDoom obtained by random PPA.

If it's not possible, how difficult would it be for GZDoom to become a Snap itself?

Thank you for this awesome game and your time!

**Comment by mcphail** [comment]
Hi @chasbel2112. Thanks for your kind words.

The gzdoom I ship in the snap package is entirely vanilla, but my launcher mangles the command line so it isn't possible to run other wads directly from the snap. I'm reluctant to change that as I want the engine to be invisible to the end user.

On the other hand, my snapcraft.yaml could be trivially adapted to produce a gzdoom snap without the bundled boa iwad. I'm probably not the best person to do that as I don't use gzdoom for anything else and I'm likely to make errors in the presentation. But it'd be a nice project for an enthusiastic gzdoom user to take on (and possibly submit upstream when perfected). If you're interested in trying, I'd be happy to help!

**Comment by HellsBells24** [comment]
While I am an enthusiastic GZDoom user, I'm afraid that enthusiasm is geared towards using it to play as opposed to creating the darn thing. That said, how trivial are we talking? This a job that could be done by following simple instructions, or should anyone who attempts go get themselves a Linux Academy subscription?

**Comment by mcphail** [comment]
It'd take about 15 minutes to adapt the boa snapcraft.yaml into one for gzdoom. The hassles come with tweaking it, supporting it and keeping it updated. I wouldn't be able to commit to that, I'm afraid, as it doesn't scratch an itch for me.

Maybe someone will swing by and run with it :)
