### ISSUE TITLE
Very low performance

### ISSUE THREAD

**Issue by rnz** [mcphail/boa#4]
CPU: AMD FX-8320E @ 4GHz
RAM: 32GiB 1866MHz
GPU: Radeon RX480 8GiB
Storage: SSD
OS: Xubuntu 18.04  with kernel 4.15.0-36-generic, gpu driver amdgpu - opensource
with Mesa 18.2.2 padoka PPA
```
OpenGL vendor string: X.Org
OpenGL renderer string: AMD Radeon (TM) RX 480 Graphics (POLARIS10, DRM 3.23.0, 4.15.0-36-generic, LLVM 7.0.0)
OpenGL core profile version string: 4.5 (Core Profile) Mesa 18.2.2 - padoka PPA
OpenGL core profile shading language version string: 4.50
OpenGL core profile context flags: (none)
OpenGL core profile profile mask: core profile
```

But game use Mesa 17.2.8 (Core profile)
```
GZDoom g3.3.2 - 2018-04-12 21:44:48 +0200 - SDL version
Compiled on Apr 14 2018
...
CPU Vendor ID: AuthenticAMD
  Name: AMD FX-8320E Eight-Core Processor 
  Family 21 (21), Model 2, Stepping 0
  Features: SSE2 SSE3 SSSE3 SSE4.1 SSE4.2 HyperThreading
I_InitSound: Initializing OpenAL
...
GL_VENDOR: X.Org
GL_RENDERER: AMD POLARIS10 (DRM 3.23.0 / 4.15.0-36-generic, LLVM 5.0.0)
GL_VERSION: 4.5 (Core Profile) Mesa 17.2.8 (Core profile)
GL_SHADING_LANGUAGE_VERSION: 4.50
```

9-10 fps in menu, 3-10 fps on Exodus map at begining 
I read this - https://realm667.com/index.php/en/forum-board/closed-issues/838-serious-performance-issues-with-wolfendoom-blade-of-agony#5115
I try tune - effect is very low.

Also Exodus map when load - drop configuration

**Comment by rnz** [comment]
I compile gzdoom from master branch of git://github.com/coelckers/gzdoom.git and now game is fine

**Comment by mcphail** [comment]
Thanks for the bug report. I haven't had much feedback from people using mesa and AMD cards, so this is very helpful.

I'm going to try to look at this next week. I'm not sure if the performance problem comes from my build or if it is something to do with the way snaps cope with the mesa drivers. Would you be able to test some builds when I've had a chance to think about this?
