### ISSUE TITLE
License

### ISSUE THREAD

**Issue by maymage** [mcphail/boa#5]
Hi, 

the license on 

https://snapcraft.io/boa 

appears as proprietary, while boa is to be released under the MIT. 

Best

**Comment by mcphail** [comment]
Thanks. It is a tricky one, because there's an explicit restriction on the github page on using the mod without permission. Unfortunately, I don't think that conforms with any open source licence, which is why I've set it to "proprietary".

**Comment by maymage** [comment]
I guess, you should clarify this then... 

See for instance https://github.com/Realm667/WolfenDoom/issues/167#issuecomment-713657909 and the discussion around.

**Comment by mcphail** [comment]
The upstream project is quite explicit about this:

"This repository is for development and testing purposes. Contributions are welcome, but you are NOT ALLOWED to use any un-released material for your own projects without our permission!"

"Important: This is only meant for development and testing purposes. You are NOT ALLOWED to use material from this repository for your own projects. Important: This repository is for development and testing purposes, you are NOT ALLOWED to use the copyrighted material for your own projects without our permission!"

Whilst some of the contributors may be using open source licences, I think it is clear from the above that not all the code and assets are freely available. As such, I need to keep the licence as "proprietary", I'm afraid. Sorry.
