### ISSUE TITLE
Snapcraft language issue

### ISSUE THREAD

**Issue by mrstobbe** [mcphail/boa#6]
Contact leads me to github, so I'm submitting an issue here even though it's not a code issue. At https://snapcraft.io/boa I noticed you used "Orchestra-quality game music" as a highlight point for the game.

That's a really confusing statement. Either music is orchestrational in nature or it's not. It's not a quality thing and there can be very, very bad music that involves an orchestra. Basically, what does that even mean? That's like saying "Electronic-quality game music" or "Acoustic drums-quality music." You're confusing composition attributes with quality attributes.

I would offer a suggestion to fix, but I really don't know what you are actually trying to say here. Sorry :(

**Comment by mcphail** [comment]
I agree the wording is a little awkward. As a packager, though, I'm merely copying the blurb from the upstream project. I don't think it is my place to alter that, so I'll close this issue. Thanks for taking the time to report.
